### ISSUE TITLE
Spring framework java 1.8 issue

### ISSUE THREAD

**Issue by ahmedhelmahdy** [kuali/kc#1587]
The Springframework version is probably out of date, as it produces 'wrong class format' exception while creating the beans...

**Comment by blackcathacker** [comment]
This issue is actually more related to drools and a dependency on a library called mvel. We experienced this but thought it was resolved by updating drools and mvel. Have you tried the most recently released version? 1506 to see if that solves the issue for you?

**Comment by ahmedhelmahdy** [comment]
I'm using the latest version 1506.70-SNAPSHOT; I noticed the pom.xml has <mvel.version>2.2.4.Final</mvel.version> not 2.2.5... would the be the reason?

**Comment by ahmedhelmahdy** [comment]
It still doesn't work after using mvel version 2.2.5...

**Comment by leoherbie** [comment]
Is this an issue or can it be closed?
