### ISSUE TITLE
Kuali copyright/license should not be on third-party JS

### ISSUE THREAD

**Issue by kgeis** [kuali/kc#1617]
The commit [KRACOEUS-8762: License header updates](https://github.com/kuali/kc/commit/d5cfb7fef63dc1c0fbdcfb5ff6aa41ee87d2b9d3) added Kuali copyright/license headers to third-party libraries in coeus-webapp/src/main/webapp/scripts. These should be removed.

**Comment by tdurkin** [comment]
Thanks, Ken. We'll get this resolved ASAP.

**Comment by tdurkin** [comment]
This was addressed in our September release.
