### ISSUE TITLE
Fancybox license incompatible with AGPL

### ISSUE THREAD

**Issue by kgeis** [kuali/kc#1618]
KC includes a JavaScript library Fancybox 2. It's [license](http://www.fancyapps.com/fancybox/#license) is not compatible with KC's AGPL license. This library should be removed.

**Comment by tdurkin** [comment]
Thanks for bringing this to our attention. We're going to move as quickly as possible to remove this library.

**Comment by tdurkin** [comment]
This was addressed in our September release.
